M48
; DRILL file {KiCad 8.0.4} date 2024-10-31T19:52:37+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-31T19:52:37+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0402
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.4331
%
G90
G05
T1
X6.2008Y-3.4441
X7.0276Y-3.4441
T2
X3.88Y-3.83
X7.5414Y-3.83
M30
